# Generated by Django 2.2.10 on 2021-02-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_theme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='license',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_period',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
